#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=16
#PBS -N CDA
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtual env
echo "loading virtual env"
source activate qiime

#Core Diversity Analysis
core_diversity_analyses.py -o CDA -i merged_core_95_2.biom -m merged_edit.tsv -e 34003 -t ~/2018_02_smb/OTU18/97_otus.tree -a -O 8

#Sampling depth set at 34003 to analyse all relevant samples

source deactivate


