#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=16
#PBS -N 2018join
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtual env
echo "loading virtual env"
source activate qiime

#Core Diversity Analysis
core_diversity_analyses.py -o COA2 -i ~/2016_02_smb/otus/otu_table.biom -m ~/2016_02_smb/map.tsv -e 34003 -t ~/2016_02_smb/otus/97_otus.tree -a -O 8

source deactivate


