#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=16
#PBS -N corebiome
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtual env
echo "loading virtual env"
source activate qiime

#Create Core Microbiome for 10/17 samples (50% - 100% abundance)
compute_core_microbiome.py -i ~/2018_02_smb/OTU18/otu_table.biom -o ./commits/2018_02_smb/CoreBiom --min_fraction_for_core 0.50

source deactivate
