#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=8
#PBS -N groupsig
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime

#Kruskal-Wallis group significance test
group_significance.py -i merged_core_95.biom -m merged_map_95.tsv -c Year -o kw2.txt

source deactivate
