#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=8
#PBS -N heatmap
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime

#Create Core biome (95% abundance) Heatmap pdf
make_otu_heatmap.py -i merged_core_95_2.biom -o heatmap2.pdf

#Create Core biome (95% abundance) Heatmap png
make_otu_heatmap.py -i merged_core_95_2.biom -o heatmap2.png -g png

source deactivate
