#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=8
#PBS -N 2018join
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime

merge_otu_tables.py -i core_table_95_16.biom,core_table_95_17.biom,core_table_95_park.biom -o merged_core_95.biom

soure deactivate
