#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=8
#PBS -N mergefiles
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime

#OTU tables for all samples merged
merge_otu_tables.py -i core_table_95_16.biom,core_table_95_17.biom,core_table_95_18.biom -o merged_core_95.biom

#Mapping files for all samples merged
merge_mapping_files.py -m map18.tsv,map16.tsv,map17.tsv -o merged_map.tsv

source deactivate
