#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=8
#PBS -N mergefiles
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime

#OTU tables for all Core biome (95% abundance) samples merged
merge_otu_tables.py -i ~/2018_02_smb/CoreBiom18/core_table_95_16.biom,~/2017_03_smb/CoreBiom17/core_table_95_17.biom,~/2016_02_smb/CoreBiom16/core_table_95_18.biom -o merged_core_95.biom

#Mapping files for all samples merged
merge_mapping_files.py -m ~/2018_02_smb/map18.tsv,~/2016_02_smb/map16.tsv,~/2017_03_smb/map17.tsv -o merged_map.tsv

source deactivate
