#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=16
#PBS -N 2018join
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtual env
echo "loading virtual env"
source activate qiime

#Closed Reference OTUs Picked
pick_closed_reference_otus.py -i ~/2017_03_smb/slout/seqs.fna -o ~/2017_03_smb/otus -a -O 8

source deactivate



