#!/bin/bash --login
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2017job
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime
# setting temporary directory
export TMPDIR=~/qiime_tmp

split_libraries_fastq.py \
-m ~/2017_03_smb/map.tsv \
-i ~/2017_03_smb/Read1.fastq.gz \
-b ~/2017_03_smb/Index.fastq.gz \
-o ~/2017_03_smb/slout \
-q 19 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes \
--barcode_type 12

source deactivate
